"use client";
import { useParams } from 'next/navigation';
import PageShell from '@/components/layout/page-shell';
import { EmptyState } from '@/components/shared/empty-state';
import { Button } from '@/components/ui/button';
import { ErrorState } from '@/components/ui/error-state';
import { ForbiddenState } from '@/components/ui/forbidden-state';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { useFinanceReceipt } from '@/hooks/use-finance';
import { formatMoneyMinor } from '@/lib/format';
import { AuthorizationError, permissions } from '@/lib/authorization/permissions';

export default function ReceiptPage() { const { id } = useParams<{ id: string }>(); const query = useFinanceReceipt(id); const record = query.data; return <PageShell title="Payment receipt" description="Print-friendly record of a simulated payment." permission={permissions.financeView}>{query.isLoading ? <div role="status" className="flex justify-center p-12"><LoadingSpinner /></div> : query.error instanceof AuthorizationError ? <ForbiddenState title="Receipt access denied" description="You are not allowed to view this receipt." backLink="/finance" /> : query.isError ? <ErrorState title="Receipt is unavailable" description="Try refreshing this record." onRetry={() => void query.refetch()} /> : !record ? <EmptyState title="Receipt not found" description="This payment receipt could not be located." action={<Button asChild variant="outline" href="/finance">Back to finance</Button>} /> : <article className="mx-auto max-w-2xl space-y-5 rounded-lg border bg-card p-6 print:border-0 print:p-0"><header className="border-b pb-4"><p className="text-sm text-muted-foreground">{record.school}</p><h2 className="text-xl font-semibold">Official receipt</h2><p className="text-sm">{record.payment.receiptNumber}</p></header><dl className="grid grid-cols-2 gap-3 text-sm"><dt>Student</dt><dd>{record.student?.firstName} {record.student?.lastName}</dd><dt>Invoice</dt><dd>{record.invoice.invoiceNumber}</dd><dt>Payment date</dt><dd>{record.payment.paymentDate}</dd><dt>Method</dt><dd>{record.payment.method.replace('_', ' ')}</dd><dt>Reference</dt><dd>{record.payment.reference}</dd><dt>Recorded by</dt><dd>{record.payment.recordedBy}</dd><dt>Amount received</dt><dd className="font-semibold">{formatMoneyMinor(record.payment.amountMinor)}</dd><dt>Remaining balance</dt><dd>{formatMoneyMinor(record.invoice.outstandingMinor)}</dd></dl><p className="rounded-md border p-3 text-sm">Simulated record only. No funds were transferred.</p><Button className="print:hidden" onClick={() => window.print()}>Print receipt</Button></article>}</PageShell>; }
