import {
  SettingsRecord,
  TenantRecord,
  UserRecord,
  TeacherProfileRecord,
  StudentRecord,
  ClassRecord,
  AuditEventRecord,
  SubjectRecord,
  AcademicYearRecord,
  TermRecord,
  TeacherAssignmentRecord,
  EnrollmentRecord,
  AdmissionApplicationRecord,
  AttendanceRecord,
  AssessmentRecord,
  AssessmentResultRecord,
  AssessmentCategoryRecord,
  GradeScaleRecord,
  FeeStructureRecord, FeeItemRecord, StudentChargeRecord, InvoiceRecord, InvoiceLineItemRecord, PaymentRecord,
} from "../types";

export const defaultTenant: TenantRecord = {
  id: "tenant-1",
  name: "CarePoint Community School",
  subdomain: "demo",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const defaultUsers: UserRecord[] = [
  {
    id: "user-teacher-2",
    tenantId: defaultTenant.id,
    username: "mrs.smith",
    email: "mrs.smith@carepoint.demo",
    password: "password",
    firstName: "Sarah",
    lastName: "Smith",
    role: "TEACHER",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-teacher-3",
    tenantId: defaultTenant.id,
    username: "mr.jones",
    email: "mr.jones@carepoint.demo",
    password: "password",
    firstName: "Michael",
    lastName: "Jones",
    role: "TEACHER",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-schoolit-1",
    tenantId: defaultTenant.id,
    username: "schoolit",
    email: "schoolit@carepoint.demo",
    password: "password",
    firstName: "School",
    lastName: "IT",
    role: "IT_ADMIN",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-admin-1",
    tenantId: defaultTenant.id,
    username: "admin",
    email: "admin@carepoint.demo",
    password: "password",
    firstName: "School",
    lastName: "Admin",
    role: "ADMIN",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-teacher-1",
    tenantId: defaultTenant.id,
    username: "teacher",
    email: "teacher@carepoint.demo",
    password: "password",
    firstName: "Demo",
    lastName: "Teacher",
    role: "TEACHER",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-parent-1",
    tenantId: defaultTenant.id,
    username: "parent",
    email: "parent@carepoint.demo",
    password: "password",
    firstName: "Demo",
    lastName: "Parent",
    role: "PARENT",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultTeacherProfiles: TeacherProfileRecord[] = [
  {
    id: "teacher-profile-1",
    tenantId: defaultTenant.id,
    userId: "user-teacher-1",
    staffId: "CP-T-001",
    qualification: "Bachelor of Education",
    specialization: "Mathematics",
    employmentDate: "2024-09-01",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultStudents: StudentRecord[] = [
  {
    id: "student-3",
    tenantId: "tenant-1",
    firstName: "Alice",
    lastName: "Wonder",
    enrollmentId: "enr-3",
    currentClassId: "class-1",
    dateOfBirth: "2010-08-15",
    guardianId: "user-parent-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "student-4",
    tenantId: "tenant-1",
    firstName: "Bob",
    lastName: "Builder",
    enrollmentId: "enr-4",
    currentClassId: "class-1",
    dateOfBirth: "2011-01-20",
    guardianId: "user-parent-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "student-1",
    tenantId: "tenant-1",
    firstName: "Demo",
    lastName: "Student 1",
    enrollmentId: "enr-1",
    currentClassId: "class-1",
    dateOfBirth: "2010-05-10",
    guardianId: "user-parent-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "student-2",
    tenantId: "tenant-1",
    firstName: "Demo",
    lastName: "Student 2",
    enrollmentId: "enr-2",
    currentClassId: "class-1",
    dateOfBirth: "2011-03-20",
    guardianId: "user-parent-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultClasses: ClassRecord[] = [
  {
    id: "class-1",
    tenantId: "tenant-1",
    name: "Grade 10A",
    gradeLevel: "Grade 10",
    academicYearId: "year-1",
    formTeacherId: "user-teacher-1",
    capacity: 30,
  },
  {
    id: "class-2",
    tenantId: "tenant-1",
    name: "Grade 10A",
    gradeLevel: "Grade 10",
    academicYearId: "year-2",
    capacity: 30,
  },
  {
    id: "class-3",
    tenantId: "tenant-1",
    name: "Grade 11A",
    gradeLevel: "Grade 11",
    academicYearId: "year-2",
    capacity: 30,
  },
];

export const defaultAuditLogs: AuditEventRecord[] = [];

const financeCreatedAt = "2026-09-01T09:00:00.000Z";
export const defaultFeeStructures: FeeStructureRecord[] = [{ id: "fee-structure-demo", tenantId: "tenant-1", name: "Grade 10A · First Term", academicYearId: "year-1", termId: "term-1", schoolClassId: "class-1", status: "ACTIVE", createdBy: "user-admin-1", createdAt: financeCreatedAt, updatedAt: financeCreatedAt }];
export const defaultFeeItems: FeeItemRecord[] = [
  { id: "fee-item-tuition", tenantId: "tenant-1", feeStructureId: "fee-structure-demo", name: "Tuition", description: "Term tuition", amountMinor: 70000 },
  { id: "fee-item-books", tenantId: "tenant-1", feeStructureId: "fee-structure-demo", name: "Books and learning materials", amountMinor: 20000 },
  { id: "fee-item-activities", tenantId: "tenant-1", feeStructureId: "fee-structure-demo", name: "Activities", amountMinor: 10000 },
];
export const defaultStudentCharges: StudentChargeRecord[] = ["student-1", "student-2", "student-3"].flatMap((studentId, index) => defaultFeeItems.map((item) => ({ id: `charge-${index + 1}-${item.id}`, tenantId: "tenant-1", studentId, enrollmentId: `enr-${index + 1}`, feeStructureId: "fee-structure-demo", feeItemId: item.id, description: item.name, amountMinor: item.amountMinor, createdAt: financeCreatedAt })));
export const defaultInvoices: InvoiceRecord[] = [
  { id: "invoice-demo-1", tenantId: "tenant-1", invoiceNumber: "INV-2026-000001", studentId: "student-1", enrollmentId: "enr-1", academicYearId: "year-1", termId: "term-1", feeStructureId: "fee-structure-demo", issuedOn: "2026-09-01", dueOn: "2026-10-15", createdBy: "user-admin-1", createdAt: financeCreatedAt },
  { id: "invoice-demo-2", tenantId: "tenant-1", invoiceNumber: "INV-2026-000002", studentId: "student-2", enrollmentId: "enr-2", academicYearId: "year-1", termId: "term-1", feeStructureId: "fee-structure-demo", issuedOn: "2026-09-01", dueOn: "2026-10-15", createdBy: "user-admin-1", createdAt: financeCreatedAt },
  { id: "invoice-demo-3", tenantId: "tenant-1", invoiceNumber: "INV-2026-000003", studentId: "student-3", enrollmentId: "enr-3", academicYearId: "year-1", termId: "term-1", feeStructureId: "fee-structure-demo", issuedOn: "2026-09-01", dueOn: "2026-10-15", createdBy: "user-admin-1", createdAt: financeCreatedAt },
];
export const defaultInvoiceLineItems: InvoiceLineItemRecord[] = defaultInvoices.flatMap((invoice) => defaultFeeItems.map((item) => ({ id: `line-${invoice.id}-${item.id}`, tenantId: "tenant-1", invoiceId: invoice.id, description: item.name, amountMinor: item.amountMinor })));
export const defaultPayments: PaymentRecord[] = [
  { id: "payment-demo-1", tenantId: "tenant-1", receiptNumber: "RCPT-2026-000001", reference: "PAY-2026-000001", invoiceId: "invoice-demo-2", studentId: "student-2", amountMinor: 40000, paymentDate: "2026-09-10", method: "CASH", status: "RECORDED", recordedBy: "user-admin-1", channel: "STAFF", createdAt: "2026-09-10T10:00:00.000Z" },
  { id: "payment-demo-2", tenantId: "tenant-1", receiptNumber: "RCPT-2026-000002", reference: "PAY-2026-000002", invoiceId: "invoice-demo-3", studentId: "student-3", amountMinor: 100000, paymentDate: "2026-09-12", method: "MOBILE_MONEY", status: "RECORDED", recordedBy: "user-admin-1", channel: "STAFF", createdAt: "2026-09-12T10:00:00.000Z" },
];

export const defaultAcademicYears: AcademicYearRecord[] = [
  {
    id: "year-1",
    tenantId: "tenant-1",
    name: "2026/2027",
    startDate: "2026-09-01T00:00:00Z",
    endDate: "2027-07-31T00:00:00Z",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "year-2",
    tenantId: "tenant-1",
    name: "2027/2028",
    startDate: "2027-09-01T00:00:00Z",
    endDate: "2028-07-31T00:00:00Z",
    status: "UPCOMING",
    createdAt: new Date().toISOString(),
  },
];

export const defaultTerms: TermRecord[] = [
  {
    id: "term-1",
    tenantId: "tenant-1",
    academicYearId: "year-1",
    name: "First Term",
    startDate: "2026-09-01T00:00:00Z",
    endDate: "2026-12-15T00:00:00Z",
    isMandatory: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "term-2",
    tenantId: "tenant-1",
    academicYearId: "year-1",
    name: "Second Term",
    startDate: "2027-01-05T00:00:00Z",
    endDate: "2027-04-10T00:00:00Z",
    isMandatory: true,
    createdAt: new Date().toISOString(),
  },
];

export const defaultSubjects: SubjectRecord[] = [
  {
    id: "sub-1",
    tenantId: "tenant-1",
    name: "Mathematics",
    code: "MATH101",
    department: "Science",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sub-2",
    tenantId: "tenant-1",
    name: "English Literature",
    code: "ENG101",
    department: "Arts",
    createdAt: new Date().toISOString(),
  },
];

export const defaultTeacherAssignments: TeacherAssignmentRecord[] = [
  {
    id: "ta-1",
    tenantId: "tenant-1",
    teacherId: "user-teacher-1",
    subjectId: "sub-1",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    termId: "term-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "ta-2",
    tenantId: "tenant-1",
    teacherId: "user-teacher-1",
    subjectId: "sub-2",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    termId: "term-1",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "ta-3",
    tenantId: "tenant-1",
    teacherId: "user-teacher-1",
    subjectId: "sub-1",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    termId: "term-2",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
  },
];

export const defaultEnrollments: EnrollmentRecord[] = [
  {
    id: "enr-3",
    tenantId: "tenant-1",
    studentId: "student-3",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    status: "ACTIVE",
    enrolledAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "enr-4",
    tenantId: "tenant-1",
    studentId: "student-4",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    status: "ACTIVE",
    enrolledAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "enr-1",
    tenantId: "tenant-1",
    studentId: "student-1",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    status: "ACTIVE",
    enrolledAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "enr-2",
    tenantId: "tenant-1",
    studentId: "student-2",
    schoolClassId: "class-1",
    academicYearId: "year-1",
    status: "ACTIVE",
    enrolledAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const defaultAdmissions: AdmissionApplicationRecord[] = [
  {
    id: "adm-2",
    tenantId: "tenant-1",
    studentFirstName: "Lucy",
    studentLastName: "Pevensie",
    studentDateOfBirth: "2016-01-12",
    gender: "Female",
    relationship: "PARENT",
    guardianName: "Demo Guardian",
    guardianEmail: "parent@carepoint.demo",
    guardianPhone: "555-0101",
    applyingForClassId: "class-1",
    applyingForYearId: "year-1",
    status: "PENDING",
    submittedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "adm-3",
    tenantId: "tenant-1",
    studentFirstName: "Edmund",
    studentLastName: "Pevensie",
    studentDateOfBirth: "2014-06-25",
    gender: "Male",
    relationship: "PARENT",
    guardianName: "Demo Guardian",
    guardianEmail: "parent@carepoint.demo",
    guardianPhone: "555-0101",
    applyingForClassId: "class-1",
    applyingForYearId: "year-1",
    status: "UNDER_REVIEW",
    submittedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "adm-1",
    tenantId: "tenant-1",
    studentFirstName: "Demo",
    studentLastName: "Applicant",
    studentDateOfBirth: "2015-05-15",
    gender: "Female",
    relationship: "GUARDIAN",
    guardianName: "Demo Guardian",
    guardianEmail: "parent@carepoint.demo",
    guardianPhone: "555-0100",
    applyingForClassId: "class-1",
    applyingForYearId: "year-1",
    status: "SUBMITTED",
    submittedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const defaultAttendance: AttendanceRecord[] = [
  {
    id: "att-2",
    tenantId: "tenant-1",
    studentId: "student-2",
    schoolClassId: "class-1",
    date: new Date().toISOString().split("T")[0],
    status: "PRESENT",
    termId: "term-1",
    academicYearId: "year-1",
    recordedById: "user-teacher-1",
    createdAt: new Date().toISOString(),
  },
  {
    id: "att-3",
    tenantId: "tenant-1",
    studentId: "student-3",
    schoolClassId: "class-1",
    date: new Date().toISOString().split("T")[0],
    status: "ABSENT",
    termId: "term-1",
    academicYearId: "year-1",
    recordedById: "user-teacher-1",
    createdAt: new Date().toISOString(),
  },
  {
    id: "att-4",
    tenantId: "tenant-1",
    studentId: "student-4",
    schoolClassId: "class-1",
    date: new Date().toISOString().split("T")[0],
    status: "LATE",
    termId: "term-1",
    academicYearId: "year-1",
    recordedById: "user-teacher-1",
    createdAt: new Date().toISOString(),
  },
  {
    id: "att-1",
    tenantId: "tenant-1",
    studentId: "student-1",
    schoolClassId: "class-1",
    date: new Date().toISOString().split("T")[0],
    status: "PRESENT",
    termId: "term-1",
    academicYearId: "year-1",
    recordedById: "user-teacher-1",
    createdAt: new Date().toISOString(),
  },
];

const assessmentSeededAt = new Date().toISOString();

export const defaultAssessmentCategories: AssessmentCategoryRecord[] = [
  { id: "category-class-test", tenantId: defaultTenant.id, name: "Class test", code: "CLASS_TEST", isActive: true, createdAt: assessmentSeededAt },
  { id: "category-assignment", tenantId: defaultTenant.id, name: "Assignment", code: "ASSIGNMENT", isActive: true, createdAt: assessmentSeededAt },
  { id: "category-exam", tenantId: defaultTenant.id, name: "Examination", code: "EXAM", isActive: true, createdAt: assessmentSeededAt },
  { id: "category-other", tenantId: defaultTenant.id, name: "Other", code: "OTHER", isActive: true, createdAt: assessmentSeededAt },
];

export const defaultGradeScales: GradeScaleRecord[] = [
  {
    id: "grade-scale-2026-2027", tenantId: defaultTenant.id, academicYearId: "year-1",
    name: "CarePoint 2026/2027", isActive: true, createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
    bands: [
      { id: "band-a", grade: "A", minimumPercentage: 80, maximumPercentage: 100, gradePoint: 4, remark: "Excellent", sortOrder: 1 },
      { id: "band-b", grade: "B", minimumPercentage: 70, maximumPercentage: 79.99, gradePoint: 3, remark: "Very good", sortOrder: 2 },
      { id: "band-c", grade: "C", minimumPercentage: 60, maximumPercentage: 69.99, gradePoint: 2, remark: "Good", sortOrder: 3 },
      { id: "band-d", grade: "D", minimumPercentage: 50, maximumPercentage: 59.99, gradePoint: 1, remark: "Satisfactory", sortOrder: 4 },
      { id: "band-e", grade: "E", minimumPercentage: 40, maximumPercentage: 49.99, gradePoint: 0.5, remark: "Needs improvement", sortOrder: 5 },
      { id: "band-f", grade: "F", minimumPercentage: 0, maximumPercentage: 39.99, gradePoint: 0, remark: "Below expectations", sortOrder: 6 },
    ],
  },
];

export const defaultAssessments: AssessmentRecord[] = [
  {
    id: "assessment-1",
    tenantId: defaultTenant.id,
    teacherAssignmentId: "ta-1",
    title: "First Term Mathematics Assessment",
    termId: "term-1",
    classId: "class-1",
    subjectId: "sub-1",
    categoryId: "category-exam",
    description: "First term mathematics final assessment.",
    assessmentDate: "2026-12-10",
    maximumScore: 100,
    weightPercent: 100,
    createdBy: "user-admin-1",
    status: "DRAFT",
    isCurrentFinal: true,
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-2",
    tenantId: defaultTenant.id,
    teacherAssignmentId: "ta-2",
    title: "First Term English Assessment",
    termId: "term-1",
    classId: "class-1",
    subjectId: "sub-2",
    categoryId: "category-exam",
    description: "First term English final assessment.",
    assessmentDate: "2026-12-11",
    maximumScore: 100,
    weightPercent: 100,
    createdBy: "user-admin-1",
    status: "DRAFT",
    isCurrentFinal: false,
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-3",
    tenantId: defaultTenant.id,
    teacherAssignmentId: "ta-3",
    title: "Second Term Mathematics Assessment",
    termId: "term-2",
    classId: "class-1",
    subjectId: "sub-1",
    categoryId: "category-class-test",
    description: "Rejected assessment sample.",
    assessmentDate: "2027-03-10",
    maximumScore: 100,
    weightPercent: 100,
    createdBy: "user-admin-1",
    status: "REJECTED",
    isCurrentFinal: false,
    rejectionReason:
      "Please review the assessment details before creating a replacement.",
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
    rejectedAt: assessmentSeededAt,
  },
];

export const defaultAssessmentResults: AssessmentResultRecord[] = [
  {
    id: "assessment-result-1",
    tenantId: defaultTenant.id,
    assessmentId: "assessment-1",
    enrollmentId: "enr-1",
    studentId: "student-1",
    score: 86,
    enteredBy: "user-teacher-1",
    status: "FINALIZED",
    gradingScaleId: "grade-scale-2026-2027",
    finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-2",
    tenantId: defaultTenant.id,
    assessmentId: "assessment-1",
    enrollmentId: "enr-2",
    studentId: "student-2",
    score: 42,
    enteredBy: "user-teacher-1",
    status: "FINALIZED",
    gradingScaleId: "grade-scale-2026-2027",
    finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-4", tenantId: defaultTenant.id, assessmentId: "assessment-1",
    enrollmentId: "enr-3", studentId: "student-3", score: 74,
    enteredBy: "user-teacher-1", status: "FINALIZED", gradingScaleId: "grade-scale-2026-2027", finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-5", tenantId: defaultTenant.id, assessmentId: "assessment-1",
    enrollmentId: "enr-4", studentId: "student-4", score: 63,
    enteredBy: "user-teacher-1", status: "FINALIZED", gradingScaleId: "grade-scale-2026-2027", finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-3",
    tenantId: defaultTenant.id,
    assessmentId: "assessment-2",
    enrollmentId: "enr-1",
    studentId: "student-1",
    score: 91,
    enteredBy: "user-teacher-1",
    status: "FINALIZED",
    gradingScaleId: "grade-scale-2026-2027",
    finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt,
    updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-6", tenantId: defaultTenant.id, assessmentId: "assessment-2",
    enrollmentId: "enr-2", studentId: "student-2", score: 78,
    enteredBy: "user-teacher-1", status: "FINALIZED", gradingScaleId: "grade-scale-2026-2027", finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-7", tenantId: defaultTenant.id, assessmentId: "assessment-2",
    enrollmentId: "enr-3", studentId: "student-3", score: 67,
    enteredBy: "user-teacher-1", status: "FINALIZED", gradingScaleId: "grade-scale-2026-2027", finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
  },
  {
    id: "assessment-result-8", tenantId: defaultTenant.id, assessmentId: "assessment-2",
    enrollmentId: "enr-4", studentId: "student-4", score: 55,
    enteredBy: "user-teacher-1", status: "FINALIZED", gradingScaleId: "grade-scale-2026-2027", finalizedAt: assessmentSeededAt,
    createdAt: assessmentSeededAt, updatedAt: assessmentSeededAt,
  },
];

export const defaultSettings: SettingsRecord[] = [
  {
    id: "settings-1",
    tenantId: "tenant-1",
    institutionName: "CarePoint Community School",
    contactEmail: "contact@carepoint.demo",
    contactPhone: "+1234567890",
    address: "12 CarePoint Avenue, Accra",
    primaryColor: "#0f172a",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
