"use client";
import Link from 'next/link';
import { useParams } from 'next/navigation';
import PageShell from '@/components/layout/page-shell';
import { EmptyState } from '@/components/shared/empty-state';
import { Button } from '@/components/ui/button';
import { ErrorState } from '@/components/ui/error-state';
import { ForbiddenState } from '@/components/ui/forbidden-state';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { useStudentFees } from '@/hooks/use-finance';
import { formatMoneyMinor } from '@/lib/format';
import { AuthorizationError, permissions } from '@/lib/authorization/permissions';

export default function ParentFeesPage() { const { studentId } = useParams<{ studentId: string }>(); const query = useStudentFees(studentId); const data = query.data; return <PageShell title="Fees and payments" description="Read-only financial information for your child." permission={permissions.parentFeesView}>{query.isLoading ? <div role="status" className="flex justify-center p-12"><LoadingSpinner /></div> : query.error instanceof AuthorizationError ? <ForbiddenState title="Fee access denied" description="This child’s fee information is not available to your account." backLink={`/parent-children/${studentId}`} /> : query.isError ? <ErrorState title="Unable to load fee information" description="Access is limited to children linked to your account." onRetry={() => void query.refetch()} /> : !data ? <EmptyState title="Student fee information is unavailable" description="This child’s fee information could not be loaded." action={<Button asChild variant="outline"><Link href={`/parent-children/${studentId}`}>Back to child profile</Link></Button>} /> : <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{data.student.firstName} {data.student.lastName}</h2><Button asChild variant="outline"><Link href={`/parent-children/${studentId}`}>Back to child profile</Link></Button></div>{data.invoices.length ? data.invoices.map((invoice) => <article key={invoice.id} className="space-y-3 rounded-lg border bg-card p-5"><header><h3 className="font-semibold">{invoice.invoiceNumber}</h3><p className="text-sm text-muted-foreground">{invoice.yearName} · {invoice.termName} · Due {invoice.dueOn} · {invoice.status.replace('_', ' ')}</p></header><ul className="space-y-1 text-sm">{invoice.lineItems.map((line) => <li key={line.id} className="flex justify-between gap-2"><span>{line.description}</span><span>{formatMoneyMinor(line.amountMinor)}</span></li>)}</ul><dl className="grid grid-cols-2 gap-2 border-t pt-3 text-sm"><dt>Total</dt><dd className="text-right">{formatMoneyMinor(invoice.totalMinor)}</dd><dt>Paid</dt><dd className="text-right">{formatMoneyMinor(invoice.paidMinor)}</dd><dt>Outstanding</dt><dd className="text-right font-semibold">{formatMoneyMinor(invoice.outstandingMinor)}</dd></dl><h4 className="text-sm font-medium">Payments</h4>{data.payments.filter((p) => p.invoiceId === invoice.id).map((payment) => <p key={payment.id} className="flex flex-wrap justify-between gap-2 text-sm">{payment.paymentDate} · {payment.reference}<span>{formatMoneyMinor(payment.amountMinor)} · <Link className="underline" href={`/parent-children/${studentId}/fees/receipts/${payment.id}`}>Receipt</Link></span></p>)}</article>) : <p className="rounded-lg border p-5">No invoices are available for this student.</p>}<p className="rounded-lg border p-4 text-sm text-muted-foreground">Payment processing is not available in this version.</p></div>}</PageShell>; }
