"use client";
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import PageShell from '@/components/layout/page-shell';
import { EmptyState } from '@/components/shared/empty-state';
import { Button } from '@/components/ui/button';
import { ErrorState } from '@/components/ui/error-state';
import { ForbiddenState } from '@/components/ui/forbidden-state';
import { Input } from '@/components/ui/input';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { useCreateInvoice, useFinanceReferences } from '@/hooks/use-finance';
import { formatMoneyMinor } from '@/lib/format';
import { AuthorizationError, permissions } from '@/lib/authorization/permissions';

export default function NewInvoicePage() { const router = useRouter(); const refs = useFinanceReferences(); const create = useCreateInvoice(); const [studentId, setStudentId] = useState(''); const [structureId, setStructureId] = useState(''); const [dueOn, setDueOn] = useState(''); const [error, setError] = useState(''); const structure = refs.data?.structures.find((r) => r.id === structureId); const total = structure?.items.reduce((n, item) => n + item.amountMinor, 0) ?? 0;
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); try { const id = await create.mutateAsync({ studentId, feeStructureId: structureId, dueOn }); router.push(`/finance/invoices/${id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create invoice.'); } }
  if (refs.isLoading) return <PageShell title="Create invoice" description="Issue a fee structure to an actively enrolled student." permission={permissions.financeManage}><div role="status" className="flex justify-center p-12"><LoadingSpinner /></div></PageShell>;
  if (refs.error instanceof AuthorizationError) return <PageShell title="Create invoice" description="Issue a fee structure to an actively enrolled student." permission={permissions.financeManage}><ForbiddenState title="Invoice creation denied" description="You do not have access to create invoices." backLink="/finance" /></PageShell>;
  if (refs.isError) return <PageShell title="Create invoice" description="Issue a fee structure to an actively enrolled student." permission={permissions.financeManage}><ErrorState title="Unable to load invoice options" description="Refresh to try again." onRetry={() => void refs.refetch()} /></PageShell>;
  if (!refs.data || !refs.data.students.length || !refs.data.structures.filter((r) => r.status === 'ACTIVE').length) return <PageShell title="Create invoice" description="Issue a fee structure to an actively enrolled student." permission={permissions.financeManage}><EmptyState title="No invoice options available" description="Create an active fee structure and an enrolled student before issuing an invoice." action={<Button asChild variant="outline"><Link href="/finance/fee-structures">Go to fee structures</Link></Button>} /></PageShell>;
  return <PageShell title="Create invoice" description="Issue a fee structure to an actively enrolled student." permission={permissions.financeManage}><form onSubmit={submit} className="max-w-2xl space-y-5 rounded-lg border bg-card p-5"><label className="block space-y-1 text-sm">Student<select required className="h-10 w-full rounded-md border bg-background px-3" value={studentId} onChange={(e) => setStudentId(e.target.value)}><option value="">Choose student</option>{refs.data.students.map((s) => <option key={s.id} value={s.id}>{s.firstName} {s.lastName}</option>)}</select></label><label className="block space-y-1 text-sm">Fee structure<select required className="h-10 w-full rounded-md border bg-background px-3" value={structureId} onChange={(e) => setStructureId(e.target.value)}><option value="">Choose structure</option>{refs.data.structures.filter((r) => r.status === 'ACTIVE').map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="block space-y-1 text-sm">Due date<Input type="date" required value={dueOn} onChange={(e) => setDueOn(e.target.value)} /></label>{structure && <section className="rounded-md border p-4"><h2 className="font-medium">Invoice summary</h2><ul className="mt-3 space-y-2">{structure.items.map((item) => <li key={item.id} className="flex justify-between gap-3 text-sm"><span>{item.name}</span><span>{formatMoneyMinor(item.amountMinor)}</span></li>)}</ul><p className="mt-3 border-t pt-3 text-right font-semibold">Total {formatMoneyMinor(total)}</p></section>}<p className="text-sm text-muted-foreground">The service verifies that the selected student is enrolled in this class for the fee structure year.</p>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={create.isPending || !structure}>{create.isPending ? 'Creating...' : 'Issue invoice'}</Button></form></PageShell>;
}
