import { useAuthStore } from '@/stores/auth-store';
import { assertPermission, AuthorizationError, permissions } from '@/lib/authorization/permissions';
import { FinanceRepository } from '../repositories/finance-repository';
import type { InvoiceStatus, PaymentMethod } from '../types';

const actor = () => { const user = useAuthStore.getState().user; if (!user || !user.tenantId) throw new AuthorizationError(); return { ...user, tenantId: user.tenantId as string }; };
const audit = (store: ReturnType<typeof FinanceRepository.read>, userId: string, tenantId: string, action: 'CREATE' | 'UPDATE', entityType: string, entityId: string, details: Record<string, unknown>) => store.auditEvents.push({ id: `audit-${globalThis.crypto.randomUUID()}`, tenantId, userId, action, entityType, entityId, details: JSON.stringify(details), createdAt: new Date().toISOString() });
const nextCode = (prefix: string, rows: object[], field: string, year = new Date().getFullYear()) => `${prefix}-${year}-${String(rows.filter((row) => String((row as Record<string, unknown>)[field]).startsWith(`${prefix}-${year}-`)).length + 1).padStart(6, '0')}`;
const invoiceAmount = (store: ReturnType<typeof FinanceRepository.read>, invoiceId: string) => store.invoiceLineItems.filter((row) => row.invoiceId === invoiceId).reduce((sum, row) => sum + row.amountMinor, 0);
const paidAmount = (store: ReturnType<typeof FinanceRepository.read>, invoiceId: string) => store.payments.filter((row) => row.invoiceId === invoiceId && row.status === 'RECORDED').reduce((sum, row) => sum + row.amountMinor, 0);
const invoiceStatus = (store: ReturnType<typeof FinanceRepository.read>, invoice: ReturnType<typeof FinanceRepository.read>['invoices'][number]): InvoiceStatus => {
  if (invoice.voidedAt) return 'VOID';
  const total = invoiceAmount(store, invoice.id); const paid = paidAmount(store, invoice.id);
  if (paid >= total) return 'PAID'; if (paid > 0) return 'PARTIALLY_PAID'; return invoice.dueOn < new Date().toISOString().slice(0, 10) ? 'OVERDUE' : 'ISSUED';
};
const viewInvoice = (store: ReturnType<typeof FinanceRepository.read>, invoice: ReturnType<typeof FinanceRepository.read>['invoices'][number]) => {
  const student = store.students.find((row) => row.id === invoice.studentId && row.tenantId === invoice.tenantId);
  const schoolClass = store.classes.find((row) => row.id === store.enrollments.find((entry) => entry.id === invoice.enrollmentId)?.schoolClassId);
  const year = store.academicYears.find((row) => row.id === invoice.academicYearId); const term = store.terms.find((row) => row.id === invoice.termId);
  const totalMinor = invoiceAmount(store, invoice.id); const paidMinor = paidAmount(store, invoice.id);
  return { ...invoice, studentName: student ? `${student.firstName} ${student.lastName}` : 'Student unavailable', className: schoolClass?.name ?? 'Class unavailable', yearName: year?.name ?? '', termName: term?.name ?? '', lineItems: store.invoiceLineItems.filter((row) => row.invoiceId === invoice.id), totalMinor, paidMinor, outstandingMinor: Math.max(totalMinor - paidMinor, 0), status: invoiceStatus(store, invoice) };
};

export class FinanceService {
  static references() {
    const user = actor(); assertPermission(permissions.financeView); const store = FinanceRepository.read();
    return { years: store.academicYears.filter((r) => r.tenantId === user.tenantId), terms: store.terms.filter((r) => r.tenantId === user.tenantId), classes: store.classes.filter((r) => r.tenantId === user.tenantId), students: store.students.filter((r) => r.tenantId === user.tenantId), structures: store.feeStructures.filter((r) => r.tenantId === user.tenantId).map((structure) => ({ ...structure, items: store.feeItems.filter((item) => item.feeStructureId === structure.id) })) };
  }
  static invoices() { const user = actor(); assertPermission(permissions.financeView); const store = FinanceRepository.read(); return store.invoices.filter((row) => row.tenantId === user.tenantId).map((row) => viewInvoice(store, row)).sort((a, b) => b.issuedOn.localeCompare(a.issuedOn)); }
  static payments() { const user = actor(); assertPermission(permissions.financeView); const store = FinanceRepository.read(); return store.payments.filter((row) => row.tenantId === user.tenantId).map((row) => ({ ...row, invoiceNumber: store.invoices.find((i) => i.id === row.invoiceId)?.invoiceNumber ?? 'Invoice unavailable', studentName: store.students.find((s) => s.id === row.studentId)?.firstName + ' ' + (store.students.find((s) => s.id === row.studentId)?.lastName ?? '') })); }
  static dashboard() { const invoices = this.invoices(); const payments = this.payments(); return { totalInvoicedMinor: invoices.filter((i) => i.status !== 'VOID').reduce((n, i) => n + i.totalMinor, 0), totalCollectedMinor: payments.filter((p) => p.status === 'RECORDED').reduce((n, p) => n + p.amountMinor, 0), outstandingMinor: invoices.filter((i) => i.status !== 'VOID').reduce((n, i) => n + i.outstandingMinor, 0), overdueMinor: invoices.filter((i) => i.status === 'OVERDUE').reduce((n, i) => n + i.outstandingMinor, 0), invoiceCount: invoices.length, paymentCount: payments.filter((p) => p.status === 'RECORDED').length, invoices } };
  static studentFees(studentId: string) { const user = actor(); const parent = user.role === 'PARENT'; assertPermission(parent ? permissions.parentFeesView : permissions.financeView); const store = FinanceRepository.read(); const student = store.students.find((s) => s.id === studentId && s.tenantId === user.tenantId && (!parent || s.guardianId === user.id)); if (!student) throw new Error('Student finance record not found.'); return { student, invoices: store.invoices.filter((i) => i.tenantId === user.tenantId && i.studentId === studentId).map((i) => viewInvoice(store, i)), payments: store.payments.filter((p) => p.tenantId === user.tenantId && p.studentId === studentId && p.status === 'RECORDED') }; }
  static createStructure(input: { name: string; academicYearId: string; termId: string; schoolClassId: string; items: { name: string; description?: string; amountMinor: number }[] }) {
    const user = actor(); assertPermission(permissions.financeManage); const name = input.name.trim();
    if (!name || !input.items.length || input.items.some((i) => !i.name.trim() || !Number.isSafeInteger(i.amountMinor) || i.amountMinor <= 0) || new Set(input.items.map((i) => i.name.trim().toLowerCase())).size !== input.items.length) throw new Error('Enter a name and fee items with unique names and positive amounts.');
    const store = FinanceRepository.read(); const year = store.academicYears.find((r) => r.id === input.academicYearId && r.tenantId === user.tenantId); const term = store.terms.find((r) => r.id === input.termId && r.tenantId === user.tenantId && r.academicYearId === input.academicYearId); const schoolClass = store.classes.find((r) => r.id === input.schoolClassId && r.tenantId === user.tenantId && r.academicYearId === input.academicYearId);
    if (!year || !term || !schoolClass) throw new Error('Select an academic year, term, and class from this school.');
    const now = new Date().toISOString(); const id = `fee-structure-${globalThis.crypto.randomUUID()}`; store.feeStructures.push({ id, tenantId: user.tenantId, name, academicYearId: year.id, termId: term.id, schoolClassId: schoolClass.id, status: 'ACTIVE', createdBy: user.id, createdAt: now, updatedAt: now });
    store.feeItems.push(...input.items.map((item) => ({ id: `fee-item-${globalThis.crypto.randomUUID()}`, tenantId: user.tenantId as string, feeStructureId: id, name: item.name.trim(), description: item.description?.trim() || undefined, amountMinor: item.amountMinor })));
    audit(store, user.id, user.tenantId, 'CREATE', 'FEE_STRUCTURE', id, { itemCount: input.items.length }); FinanceRepository.save(store); return id;
  }
  static createInvoice(input: { studentId: string; feeStructureId: string; dueOn: string }) {
    const user = actor(); assertPermission(permissions.financeManage); const store = FinanceRepository.read(); const student = store.students.find((s) => s.id === input.studentId && s.tenantId === user.tenantId); const structure = store.feeStructures.find((s) => s.id === input.feeStructureId && s.tenantId === user.tenantId && s.status === 'ACTIVE'); const enrollment = student && store.enrollments.find((e) => e.studentId === student.id && e.tenantId === user.tenantId && e.academicYearId === structure?.academicYearId && e.schoolClassId === structure?.schoolClassId && e.status === 'ACTIVE'); const items = structure && store.feeItems.filter((i) => i.feeStructureId === structure.id && i.tenantId === user.tenantId);
    if (!student || !structure || !enrollment || !items?.length || input.dueOn < new Date().toISOString().slice(0, 10)) throw new Error('Choose a student actively enrolled in the fee structure class and a valid future due date.');
    if (store.invoices.some((i) => i.studentId === student.id && i.feeStructureId === structure.id && !i.voidedAt)) throw new Error('An invoice already exists for this student and fee structure.');
    const issuedOn = new Date().toISOString().slice(0, 10); const invoiceNumber = nextCode('INV', store.invoices.filter((i) => i.tenantId === user.tenantId), 'invoiceNumber'); const id = `invoice-${globalThis.crypto.randomUUID()}`;
    store.invoices.push({ id, tenantId: user.tenantId, invoiceNumber, studentId: student.id, enrollmentId: enrollment.id, academicYearId: structure.academicYearId, termId: structure.termId, feeStructureId: structure.id, issuedOn, dueOn: input.dueOn, createdBy: user.id, createdAt: new Date().toISOString() });
    store.invoiceLineItems.push(...items.map((item) => ({ id: `invoice-line-${globalThis.crypto.randomUUID()}`, tenantId: user.tenantId as string, invoiceId: id, description: item.name, amountMinor: item.amountMinor })));
    store.studentCharges.push(...items.map((item) => ({ id: `charge-${globalThis.crypto.randomUUID()}`, tenantId: user.tenantId as string, studentId: student.id, enrollmentId: enrollment.id, feeStructureId: structure.id, feeItemId: item.id, description: item.name, amountMinor: item.amountMinor, createdAt: new Date().toISOString() })));
    audit(store, user.id, user.tenantId, 'CREATE', 'INVOICE', id, { invoiceNumber, studentId: student.id, amountMinor: items.reduce((n, item) => n + item.amountMinor, 0) }); FinanceRepository.save(store); return id;
  }
  static recordPayment(input: { invoiceId: string; amountMinor: number; paymentDate: string; method: PaymentMethod; notes?: string }) {
    const user = actor(); assertPermission(permissions.financeManage); const store = FinanceRepository.read(); const invoice = store.invoices.find((i) => i.id === input.invoiceId && i.tenantId === user.tenantId); if (!invoice) throw new Error('Invoice not found.'); const view = viewInvoice(store, invoice);
    if (view.status === 'VOID' || view.outstandingMinor <= 0) throw new Error('This invoice cannot accept another payment.');
    if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor <= 0 || input.amountMinor > view.outstandingMinor) throw new Error('Payment must be greater than zero and no more than the outstanding balance.');
    if (!['CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CARD'].includes(input.method)) throw new Error('Choose a supported payment method.');
    if (!/^\d{4}-\d{2}-\d{2}$/.test(input.paymentDate) || input.paymentDate > new Date().toISOString().slice(0, 10)) throw new Error('Enter a valid payment date that is not in the future.');
    const year = Number(input.paymentDate.slice(0, 4)); const receiptNumber = nextCode('RCPT', store.payments.filter((p) => p.tenantId === user.tenantId), 'receiptNumber', year); const reference = nextCode('PAY', store.payments.filter((p) => p.tenantId === user.tenantId), 'reference', year); const id = `payment-${globalThis.crypto.randomUUID()}`;
    store.payments.push({ id, tenantId: user.tenantId, receiptNumber, reference, invoiceId: invoice.id, studentId: invoice.studentId, amountMinor: input.amountMinor, paymentDate: input.paymentDate, method: input.method, status: 'RECORDED', recordedBy: user.id, notes: input.notes?.trim() || undefined, createdAt: new Date().toISOString() });
    audit(store, user.id, user.tenantId, 'CREATE', 'PAYMENT', id, { receiptNumber, reference, invoiceId: invoice.id, amountMinor: input.amountMinor }); FinanceRepository.save(store); return id;
  }
  static voidInvoice(id: string, reason: string) { const user = actor(); assertPermission(permissions.financeManage); const store = FinanceRepository.read(); const invoice = store.invoices.find((i) => i.id === id && i.tenantId === user.tenantId); const note = reason.trim(); if (!invoice || invoiceStatus(store, invoice) === 'VOID' || paidAmount(store, id) > 0 || note.length < 10) throw new Error('An unpaid invoice and a reason of at least 10 characters are required.'); invoice.voidedAt = new Date().toISOString(); invoice.voidReason = note; audit(store, user.id, user.tenantId, 'UPDATE', 'INVOICE_VOIDED', id, { reason: note }); FinanceRepository.save(store); }
  static receipt(id: string) { const user = actor(); const store = FinanceRepository.read(); const payment = store.payments.find((p) => p.id === id && p.tenantId === user.tenantId && p.status === 'RECORDED'); if (!payment) throw new Error('Receipt not found.'); if (user.role === 'PARENT') { assertPermission(permissions.parentFeesView); const student = store.students.find((s) => s.id === payment.studentId && s.guardianId === user.id && s.tenantId === user.tenantId); if (!student) throw new AuthorizationError(); } else assertPermission(permissions.financeView); const invoice = store.invoices.find((i) => i.id === payment.invoiceId); if (!invoice) throw new Error('Invoice not found.'); audit(store, user.id, user.tenantId, 'CREATE', 'RECEIPT_VIEWED', payment.id, { receiptNumber: payment.receiptNumber }); FinanceRepository.save(store); return { payment, invoice: viewInvoice(store, invoice), student: store.students.find((s) => s.id === payment.studentId), school: store.settings.find((s) => s.tenantId === user.tenantId)?.institutionName ?? 'School' }; }
}
